### ISSUE TITLE
Can't run the demo due to "Uncaught SyntaxError: Unexpected reserved word"

### ISSUE THREAD

**Issue by ZenCocoon** [ef4/physical-design-demo#1]
Would love to run the demo but got the following error showing up `Uncaught SyntaxError: Unexpected reserved word`

Seems to be a problem with `action.js#5` with `class Action {`

**Comment by ef4** [comment]
You may need the very newest ember-cli. The (unreleased, bleeding-edge) version of liquid-fire being used here depends on the latest ember-cli's ability to nest addons. In this case it needs babel to transpile that file.

**Comment by ZenCocoon** [comment]
Ember CLI 0.2.0-beta.1 is not enough? I need master?

I've got `ember-cli-babel` already as dependence as just just cloned your repo then `npm install` `bower install` `ember serve`

**Comment by ZenCocoon** [comment]
Actually Ember CLI 0.2.0 just got released and it now works like a charm :) Thanks
