### ISSUE TITLE
The App failing to run

### ISSUE THREAD

**Issue by izoj2013** [ef4/physical-design-demo#2]
Dear Edward,
I have followed instructions under "Installation" as given at https://github.com/ef4/physical-design-demo.
But when I run as follows:
me@mymc ~/mydir/physical-design-demo $ ember serve
version: 0.2.0
Livereload server on port 35729
Serving on http://localhost:4200/

Build successful - 3576ms.

Slowest Trees                  | Total  
-------------------------------+----------------
Babel                          | 814ms  
Babel                          | 683ms  
ES3SafeFilter                  | 631ms 

When I visit your demo app at http://localhost:4200; the page is blank!!! On Chrome, I open Ember inspector, no error. 
Mine is a linux mint 64bit, node.js v0.12.0

**Comment by IanVS** [comment]
@izoj2013 This tripped me up for a minute too.  The correct URL is: [http://localhost:4200/emberconf](http://localhost:4200/emberconf).

**Comment by izoj2013** [comment]
Many thanks. It's working.-

```
 On Friday, March 27, 2015 4:50 AM, Ian VanSchooten <notifications@github.com> wrote:
```

 @izoj2013 This tripped me up for a minute too. The correct URL is: http://localhost:4200/emberconf.—
